### ISSUE TITLE
rtoml updated, retry benchmarks

### ISSUE THREAD

**Issue by samuelcolvin** [pwwang/toml-bench#1]
Hi, I've just updated rtoml and (hopefully :crossed_fingers:) made it significantly faster, see [v0.9 release](https://github.com/samuelcolvin/rtoml/releases/tag/v0.9).

I wonder if you could re-run the benchmarks to see the relative performance?

**Comment by pwwang** [comment]
Updated, and you have made the fastest! 🎆

**Comment by samuelcolvin** [comment]
Thanks so much.
