### ISSUE TITLE
Add python 3.11 std lib toml 

### ISSUE THREAD

**Issue by samuelcolvin** [pwwang/toml-bench#2]
To benchmarks? Might be interesting.

**Comment by pwwang** [comment]
Good idea!

https://github.com/python/cpython/tree/3.11/Lib/test/test_tomllib/data

**Comment by pwwang** [comment]
Added. See https://github.com/pwwang/toml-bench/releases/tag/0.2.0

**Comment by samuelcolvin** [comment]
Cool, although that's not quite what I meant.

I was suggesting adding the tomllib toml parser that's included in the python standard library from 3.11 to the libraries benchmarked, so it's performance can be compared.

**Comment by pwwang** [comment]
Ah, I see. Will try to add it in the next version.
