### ISSUE TITLE
Add `tomllib` as a toml parser from python 3.11 

### ISSUE THREAD

**Issue by pwwang** [pwwang/toml-bench#3]
Cool, although that's not quite what I meant.

I was suggesting adding the tomllib toml parser that's included in the python standard library from 3.11 to the libraries benchmarked, so it's performance can be compared.

_Originally posted by @samuelcolvin in https://github.com/pwwang/toml-bench/issues/2#issuecomment-1312160438_

**Comment by pwwang** [comment]
@samuelcolvin Added.

See https://github.com/pwwang/toml-bench/blob/master/reports/with_python3.11.md

I didn't put the report in README.md, as not all the packages support python 3.11 yet (`pytomlpp` does not), but add a link to it in _Other Reports_ section instead.

Let's see if we can put it in README.md in the future.

**Comment by samuelcolvin** [comment]
Awesome, tomllib is quite impressive for a pure python implementation.

**Comment by pwwang** [comment]
Yes, it is. I think the idea is from `tomli` and probably implemented by `tomli`'s author as well.
