### ISSUE TITLE
Serialisation benchmarks?

### ISSUE THREAD

**Issue by samuelcolvin** [pwwang/toml-bench#4]
Sorry, me again.

Would be amazing to add serialisation to the benchmarks for the libraries which support it, as well as loading.

**Comment by pwwang** [comment]
What kind of api are we expecting, other than dump/dumps?

Do you mean the speed of dumping a dict into a string or a toml file?

**Comment by samuelcolvin** [comment]
I was thinking just `dumps`. Please excuse me being dumb, if it's already available somewhere and I missed it?

**Comment by pwwang** [comment]
No, you are not at all. The speed tests are currently just for load/loads. 

Just not sure what data to be used for the tests. Maybe we just use the dicts loaded from the toml files that are currently used for speed testing for `load/loads`?

**Comment by samuelcolvin** [comment]
Yes, that's what I would do.

**Comment by pwwang** [comment]
Sounds good to me.

**Comment by samuelcolvin** [comment]
That should guarantee that all types are tested. You could also do a round trip test to confirm libraries process data correctly in and out.

**Comment by pwwang** [comment]
It's easy for the round trip from `dict -> string -> dict`, since `dicts` are relatively easier to compare in python, but tougher from `string -> dict -> string` due to the arbitrariness of strings as there could be comments and extra spaces.

We could probably do:

```
(toml files)
   string      ->       dict      ->    string     ->      dict
                         |                                  |
                         +----------- comparison -----------+
```

**Comment by samuelcolvin** [comment]
Yes, that's what I was thinking.

I guess you could compare toml strings after the first loop when it shouldn't change anymore.

**Comment by pwwang** [comment]
> I guess you could compare toml strings after the first loop when it shouldn't change anymore.

I think this is more like a reproducibility test. The same dict should produce/be dumped into the same string.

**Comment by samuelcolvin** [comment]
True.

**Comment by pwwang** [comment]
Dumping benchmarking is added.

As for the reproducibility test, let's see if we have a better reason to add it since the tests for `None`-value behavior were already included. Other inconsistencies that I can think of for now include float number precision, date time formatting, etc. But they are not essential for a toml parser for general use.

We can open another issue if we find those problems matter in more scenarios.
